version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: playernation-db
    restart: always
    environment:
      POSTGRES_USER: playernation_user
      POSTGRES_PASSWORD: playernation_password
      POSTGRES_DB: playernation_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
